### PR TITLE
Improve docs for main function

### PR DESCRIPTION
**Pull request by davidskalinder**
I just came across this great repo -- thanks for making what looks like a big improvement on the existing Blinder-Oaxaca functionality in R!

I don't know if you're accepting PRs, but I thought I'd give this one a try.  It mostly just transfers some of the useful info from the README to the function documentation itself, so hopefully it'll be straightforward; but of course let me know if you think it needs any changes?

### CODE REVIEW

**Comment by sinanpl** [comment]
Hi David, glad you like it. I am accepting PRs. This will actually be the first one I receive, and apparently your first one as well... cheers to that! :)

Sinan

PS: I wasn't planning to actively develop this further. Basics are there, but if I remember correctly there is some functionality missing - same holds for proper testing. Feel free to play with it, happy to think along if any ideas.

**Comment by davidskalinder** [comment]
Great, thanks!  I am working on a project using Blinder-Oaxaca so I will probably do some more poking at the code along the way.  Do you want me to try to keep submitting PRs for each change, or would it be better for me to just keep changes in my fork and then do a big PR later?

Also, I don't think there's a license in the project at the moment -- do you know what you would want to use for that?

**Comment by sinanpl** [comment]
Preferring smaller PRs, unless you foresee future work that logically belongs together.

Wrt license I would consider the least restrictive one. Need to revise those though - maybe this weekend.

Looking forward to your additions!

On 21 Feb 2024, at 18:11, davidskalinder ***@***.***> wrote:

﻿

Great, thanks! I am working on a project using Blinder-Oaxaca so I will probably do some more poking at the code along the way. Do you want me to try to keep submitting PRs for each change, or would it be better for me to just keep changes in my fork and then do a big PR later?

Also, I don't think there's a license in the project at the moment -- do you know what you would want to use for that?

**Comment by davidskalinder** [comment]
> Preferring smaller PRs, unless you foresee future work that logically belongs together.

Gotcha, I'll try to keep them bite-size and in separate branches.

Thanks again!

**Comment by sinanpl** [comment]
I've added the MIT license. Thanks for notifying me about this!

**Pull request merged**
